### PR TITLE
Add a custom footer (seperate from the main menu)

### PR DESCRIPTION
**Pull request by Rick-VA**

### CODE REVIEW

**Comment by dmeijboom** [comment]
CC: @Saldoo

**Comment by reinkrul** [comment]
@Rick-VA maybe you can drop a screenshot so non-techies can review it as well?

**Comment by Rick-VA** [comment]
Screenshot 2024-03-15 115124

**Comment by Saldoo** [comment]
Ziet er goed uit @Rick-VA !
Kan ik ook op regelniveau social media icons toevoegen? Heb je ook nog een prinsscreen voor mobile? Bedankt.

**Comment by Rick-VA** [comment]
> Ziet er goed uit @Rick-VA ! Kan ik ook op regelniveau social media icons toevoegen? Heb je ook nog een prinsscreen voor mobile? Bedankt.

image
image

Ik heb nu ook de social media icons toegevoegd op regelniveau.

**Comment by Saldoo** [comment]
Top @Rick-VA!  Ziet er goed uit! @reinkrul kan je deze publiceren?

**Review by reinkrul — APPROVED** [review]

**Comment by reinkrul** [comment]
@Rick-VA appearantely this PR broke the build (https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094):

```
Run npx --no-install next build
 ⚠ Invalid next.config.js options detected: 
 ⚠     Unrecognized key(s) in object: 'images' at "experimental"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

   Linting and checking validity of types ...

Failed to compile.

./pages/index.tsx
[6](https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094#step:8:7)8:15  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
68:15  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
[7](https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094#step:8:8)8:15  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
7[8](https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094#step:8:9):15  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
[9](https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094#step:8:10)9:11  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
99:11  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a[11](https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094#step:8:12)y/alt-text

./components/Footer.tsx
24:7  Error: Missing "key" prop for element in iterator  react/jsx-key
24:7  Error: Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank
25:9  Warning: Do not use <img>. Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./components/Menu.tsx
83:6  Warning: React Hook useEffect has a missing dependency: 'router.events'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
97:7  Warning: passHref is missing. See: https://nextjs.org/docs/messages/link-passhref  @next/next/link-passhref

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Error: Process completed with exit code 1.
```

**Comment by dmeijboom** [comment]
> @Rick-VA appearantely this PR broke the build (https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094):
> 
> ```
> Run npx --no-install next build
>  ⚠ Invalid next.config.js options detected: 
>  ⚠     Unrecognized key(s) in object: 'images' at "experimental"
>  ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
> ⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
> Attention: Next.js now collects completely anonymous telemetry regarding usage.
> This information is used to shape Next.js' roadmap and prioritize features.
> You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
> https://nextjs.org/telemetry
> 
>    Linting and checking validity of types ...
> 
> Failed to compile.
> 
> ./pages/index.tsx
> [6](https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094#step:8:7)8:15  Warning: Do not use . Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
> 68:15  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
> [7](https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094#step:8:8)8:15  Warning: Do not use . Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
> 7[8](https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094#step:8:9):15  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a11y/alt-text
> [9](https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094#step:8:10)9:11  Warning: Do not use . Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
> 99:11  Warning: img elements must have an alt prop, either with meaningful text, or an empty string for decorative images.  jsx-a[11](https://github.com/nuts-foundation/nuts-webpresence/actions/runs/8415660340/job/23041129094#step:8:12)y/alt-text
> 
> ./components/Footer.tsx
> 24:7  Error: Missing "key" prop for element in iterator  react/jsx-key
> 24:7  Error: Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank
> 25:9  Warning: Do not use . Use Image from 'next/image' instead. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
> 
> ./components/Menu.tsx
> 83:6  Warning: React Hook useEffect has a missing dependency: 'router.events'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
> 97:7  Warning: passHref is missing. See: https://nextjs.org/docs/messages/link-passhref  @next/next/link-passhref
> 
> info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
> Error: Process completed with exit code 1.
> ```

Seems like this is the issue:

```
24:7  Error: Missing "key" prop for element in iterator  react/jsx-key
24:7  Error: Using target="_blank" without rel="noreferrer" (which implies rel="noopener") is a security risk in older browsers: see https://mathiasbynens.github.io/rel-noopener/#recommendations  react/jsx-no-target-blank
```

It would be nice if we ran `next lint` or something similar in the CI but we'll make a PR to fix it.

**Pull request merged**
