### PR TITLE
Deploy Nuts JSON-LD context v1.1

### PR DESCRIPTION
**Pull request by reinkrul**

### CODE REVIEW

**Review by stevenvegt — COMMENTED** [review]
So, if the v1.0 version has the old style localParams, what version is the v1 file? Should we add a v1.1 file (copy of the current state of the v1)?

**Comment by reinkrul** [comment]
I was thinking of keeping the old version available, so new version is 1.1 (and v1 would be the latest, major version). But on the other hand, it's not compatible with the previous version (when using localParameters), so it should be v2 if we kept it 100% pure. But since nobody uses it, we could just replace it?

**Comment by woutslakhorst** [comment]
Keeping the /v1.0 there is just confusing.

**Comment by reinkrul** [comment]
@woutslakhorst @stevenvegt needs re-review

**Review by woutslakhorst — APPROVED** [review]

**Comment by reinkrul** [comment]
I'm not allowed to merge.

**Pull request merged**
