### PR TITLE
Replace slider with responsive version

### PR DESCRIPTION
**Pull request by dmeijboom**
I created a simple carousel for the Nuts website but it seems like it has some issues and lacks proper responsiveness. Replaced it with Swiper which seems to work much better.

### CODE REVIEW

**Review by Saldoo — APPROVED** [review]

**Comment by Timendus** [comment]
I changed a couple of small things that I think improve the look. The only thing left that I'm not sure how to fix:

Screenshot 2023-06-22 at 10 43 52

After the first round, there is a magic right margin on high resolution screens. Looks like the `swiper-wrapper` element isn't full width anymore.

**Review by Timendus — COMMENTED** [review]
I changed a couple of small things that I think improve the look. The only thing left that I'm not sure how to fix:

Screenshot 2023-06-22 at 10 43 52

After the first round, there is a magic right margin on high resolution screens. Looks like the `swiper-wrapper` element isn't full width anymore.

**Review by dmeijboom — COMMENTED** [review]
@Timendus Feedback

**Comment by dmeijboom** [comment]
@Timendus Fixed things but removed the random stuff, I'm sure it could work somehow but unfortunately I don't have the time to fix it. At least it works now and it looks/works better than the one we're currently using (at least in my opinion).

**Review by Saldoo — APPROVED** [review]

**Review by Saldoo — APPROVED** [review]

**Pull request merged**
